#!/usr/bin/env bash
# ================================================
# ReaX Docker Entrypoint
# ================================================
# - Connects to Linera Conway Testnet
# - Builds & deploys Linera microchain app
# - Writes environment files for backend/frontend
# - Starts Linera service + backend + frontend
# ================================================

set -euo pipefail

# Configuration
TESTNET_FAUCET="${TESTNET_FAUCET:-https://faucet.testnet-conway.linera.net/}"
LINERA_SERVICE_PORT="${LINERA_SERVICE_PORT:-8081}"
BACKEND_PORT="${BACKEND_PORT:-3001}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"

# Database/Redis from compose
DB_HOST="${DB_HOST:-postgres}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-reax}"
DB_USER="${DB_USER:-admin}"
DB_PASSWORD="${DB_PASSWORD:-password}"
REDIS_HOST="${REDIS_HOST:-redis}"
REDIS_PORT="${REDIS_PORT:-6379}"

echo ""
echo "╔════════════════════════════════════════════╗"
echo "║          ReaX Platform Startup             ║"
echo "║     Microchain Social Trading Platform     ║"
echo "║          Network: Conway Testnet           ║"
echo "╚════════════════════════════════════════════╝"
echo ""

# Verify dependencies
if ! command -v linera >/dev/null 2>&1; then
  echo "❌ linera CLI not found in container"
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "❌ node not found in container"
  exit 1
fi

cd /build

# ================================================
# Wait for Infrastructure
# ================================================
echo "⏳ Waiting for PostgreSQL..."
for i in {1..60}; do
  (echo > /dev/tcp/${DB_HOST}/${DB_PORT}) >/dev/null 2>&1 && break || true
  sleep 1
done
echo "✅ PostgreSQL ready"

echo "⏳ Waiting for Redis..."
for i in {1..60}; do
  (echo > /dev/tcp/${REDIS_HOST}/${REDIS_PORT}) >/dev/null 2>&1 && break || true
  sleep 1
done
echo "✅ Redis ready"
echo ""

# ================================================
# Initialize Linera Wallet
# ================================================
echo "💼 Initializing Linera wallet (Conway Testnet)..."
linera wallet init --faucet "${TESTNET_FAUCET}" 2>/dev/null || true

echo "⛓️  Requesting chain from faucet..."
CHAIN_OUTPUT="$(linera wallet request-chain --faucet "${TESTNET_FAUCET}" 2>/dev/null || true)"
CHAIN_ID="$(echo "${CHAIN_OUTPUT}" | grep -oE '[a-f0-9]{64}' | head -n 1 || true)"

if [ -z "${CHAIN_ID}" ]; then
  # Fallback: read from wallet
  WALLET_OUTPUT="$(linera wallet show 2>/dev/null || true)"
  CHAIN_ID="$(echo "${WALLET_OUTPUT}" | grep -oE '[a-f0-9]{64}' | head -n 1 || true)"
fi

echo "✅ Chain ID: ${CHAIN_ID:-unknown}"
echo ""

# ================================================
# Build & Deploy Linera Microchain App
# ================================================
echo "📦 Building Linera microchain app (wasm32)..."
echo "   This may take 5-15 minutes on first run..."
cd linera-app
cargo build --release --target wasm32-unknown-unknown 2>&1 | tail -10

echo ""
echo "🚀 Publishing ReaX microchain application..."
APP_OUTPUT="$(linera --wait-for-outgoing-messages project publish-and-create . reax-microchain 2>&1)" || true
echo "${APP_OUTPUT}" > /build/logs/linera-deploy.log

# Try to extract full application ID (format varies by Linera version)
# First try: Look for "Application ID:" pattern
APP_ID="$(echo "${APP_OUTPUT}" | grep -oP '(?<=Application ID: )[^\s]+' || true)"

# Fallback: Look for application ID in standard format (longer than chain ID)
if [ -z "${APP_ID}" ]; then
  # Application IDs typically have format: <bytecode_id><creation_chain><creation_height>...
  APP_ID="$(echo "${APP_OUTPUT}" | grep -oE '[a-f0-9]{64,}' | tail -n 1 || true)"
fi

# Fallback: Check if app was already deployed by querying the chain
if [ -z "${APP_ID}" ]; then
  echo "⚠️  Could not extract APP_ID from output. Checking for existing applications..."
  APPS_OUTPUT="$(linera wallet show 2>/dev/null || true)"
  echo "${APPS_OUTPUT}" >> /build/logs/linera-deploy.log
  APP_ID="$(echo "${APPS_OUTPUT}" | grep -oP '(?<=Application ID: )[^\s]+' | head -n 1 || true)"
fi

cd /build

if [ -z "${APP_ID}" ]; then
  echo "⚠️  Could not determine LINERA_APP_ID"
  echo "   Check /build/logs/linera-deploy.log for details"
  echo "   Using chain ID as fallback (limited functionality)"
  APP_ID="${CHAIN_ID:-demo-app-id}"
fi

echo "✅ Linera App ID: ${APP_ID}"
echo ""

# ================================================
# Write Environment Files
# ================================================
echo "⚙️  Writing environment configuration..."

cat > backend/.env.local <<EOF
# ReaX Backend Configuration (Auto-generated by Docker)
PORT=${BACKEND_PORT}
FRONTEND_URL=http://localhost:${FRONTEND_PORT}

# Database
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

# Redis
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}

# Solana
SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}

# Jupiter DEX
JUPITER_API_URL=https://quote-api.jup.ag/v6
JUPITER_API_KEY=${JUPITER_API_KEY:-}

# Raydium DEX
RAYDIUM_API_URL=https://transaction-v1.raydium.io
RAYDIUM_PRIORITY_FEE_URL=https://api-v3.raydium.io/main/auto-fee

# Linera
LINERA_NETWORK=testnet-conway
LINERA_FAUCET_URL=${TESTNET_FAUCET}
LINERA_SERVICE_URL=http://localhost:${LINERA_SERVICE_PORT}
LINERA_RPC_URL=http://localhost:${LINERA_SERVICE_PORT}
LINERA_APP_ID=${APP_ID}
LINERA_CHAIN_ID=${CHAIN_ID}
EOF

cat > frontend/.env.local <<EOF
# ReaX Frontend Configuration (Auto-generated by Docker)
NEXT_PUBLIC_LINERA_APP_ID=${APP_ID}
NEXT_PUBLIC_LINERA_CHAIN_ID=${CHAIN_ID}
NEXT_PUBLIC_LINERA_SERVICE_URL=http://localhost:${LINERA_SERVICE_PORT}
NEXT_PUBLIC_LINERA_NETWORK=testnet-conway
NEXT_PUBLIC_LINERA_FAUCET_URL=${TESTNET_FAUCET}
NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
NEXT_PUBLIC_WS_URL=http://localhost:${BACKEND_PORT}
EOF

echo "✅ Environment files written"
echo ""

# ================================================
# Start Services
# ================================================
echo "🌐 Starting Linera service on port ${LINERA_SERVICE_PORT}..."
linera service --port "${LINERA_SERVICE_PORT}" > /build/logs/linera-service.log 2>&1 &
LINERA_PID=$!
sleep 3

echo "🔧 Starting backend API on port ${BACKEND_PORT}..."
cd /build/backend
npm run dev > /build/logs/backend.log 2>&1 &
BACKEND_PID=$!
cd /build
sleep 2

echo "🎨 Starting frontend on port ${FRONTEND_PORT}..."
cd /build/frontend
PORT="${FRONTEND_PORT}" npm run dev > /build/logs/frontend.log 2>&1 &
FRONTEND_PID=$!
cd /build
sleep 2

echo ""
echo "╔════════════════════════════════════════════╗"
echo "║       ✅ ReaX Platform Running!            ║"
echo "╠════════════════════════════════════════════╣"
echo "║  🎨 Frontend:  http://localhost:${FRONTEND_PORT}       ║"
echo "║  🔧 Backend:   http://localhost:${BACKEND_PORT}       ║"
echo "║  ⛓️  Linera:    http://localhost:${LINERA_SERVICE_PORT}       ║"
echo "╠════════════════════════════════════════════╣"
echo "║  📊 Logs: /build/logs/                     ║"
echo "╚════════════════════════════════════════════╝"
echo ""

# Create logs directory
mkdir -p /build/logs

# Keep container alive
wait -n "${LINERA_PID}" "${BACKEND_PID}" "${FRONTEND_PID}"
